// Copyright (C) 2010 European Central Bank. All rights reserved.
//
// Redistribution and use in source and binary forms,
// with or without modification, are permitted
// provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
// Neither the name of the European Central Bank
// nor the names of its contributors may be used to endorse or promote products
// derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
package eu.ecb.core.view.map {
  import ilog.maps.MapBase;
  import ilog.maps.Map;

 /**
  * This class is automatically generated by iLog Elixir.
  * Generated on: 13 November 2009 15:18:45 o'clock CET
  * Projection: PROJECTION["Lambert Azimuthal Equal Area"]
  * Simplification threshold: 0.0 meters  * Interpolation degree: 3
  **/
 /**
  * Implementation of a specialized <code>MapBase</code>.
  * 
  *  @mxml
  *  
  *  <p>
  *  The <code>&lt;ilog:EuropeMap&gt;</code> tag inherits all the tag attributes of its superclass and
  *  adds the following tag attributes:
  *  </p>
  *  <pre>
  *  &lt;ilog:EuropeMap
  *    <b>Properties</b>
  *    allowMultipleSelection="true|false"
  *    allowSelection="true|false"
  *    mapFeatures="[]"
  *    selectedFeatures="[]"
  *    symbols="[]"
  *    zoomableSymbols="true|false"
  *    allowNavigation="true|false"
  *    filterEvents="true|false"
  *    featureNames="[]"
  *    resizeCompatibility="true|false"
  *    matrix="flash.geom.Matrix"
  *    
  *    <b>Styles</b>
  *    animationDuration="0"
  *    backgroundFill="0x6A5ACD"
  *    fill="0xFAEBD7"
  *    stroke="0xA9967D"
  *    highlightFill="0xA354FF"
  *    highlightStroke="0xFFD39B"
  *    filters="[]"
  *    highlightFilters="[]"
  *    cursor="[]"
  *    showZoomReticle="true|false"
  *    
  *    <b>Events</b>
  *    mapChange="<i>No default</i>"
  *    mapItemDoubleClick="<i>No default</i>"
  *    mapItemRollOut="<i>No default</i>"
  *    mapItemRollOver="<i>No default</i>"
  *    mapItemClick="<i>No default</i>"
  *  /&gt;
  *  </pre>
  *
  *  @see ilog.maps.MapBase 

  */
  public class EuropeMap extends MapBase  {
   /**
    * @inheritDoc
    */
    public override function createMap():Map {
      return new Europe();
    }
   /**
    * @inheritDoc
    */
    public override function getString(k:String):String {
      if(resourceManager != null)
        return resourceManager.getString("Europe", k);
      return k;
    }
  }
}
